base_url = "www.cherokeelessons.com"
title = "Cherokee Lessons"
description = "Various resources for learning the Cherokee Language."
default_language = "en"
theme = "Zulma"
highlight_code = true
generate_rss = true
build_search_index = true

taxonomies = [
    {name = "categories", paginate_by = 8, rss = true},
    {name = "tags", paginate_by = 8, rss = true},
    {name = "authors", paginate_by = 8, rss = true}
]

compile_sass = true

hard_link_static = true

[slugify]
paths = "safe"
taxonomies = "safe"
anchors = "safe"

[extra]

zulma_brand = {text="Cherokee Lessons"}
zulma_theme = "superhero"
zulma_allow_theme_selection = true
zulma_menu = [
  {url = "/apps", name = "Apps"},
  {url = "/books", name = "Books and eBooks"}
]
